version: '2'
services:
  app:
    build: .
    networks:
      - app
    depends_on:
      - mysql
    ports:
      - '80:3456'

  mysql:
    image: mysql:5.7
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  app:
