version: '2'
services:
  app:
    build: .
    command: npm run dev
    networks:
      - app
    depends_on:
      - mariadb
    ports:
      - '3000:3456'

  mariadb:
    image: mariadb
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  app:
