version: '2'
services:
  app:
    build: .
    command: npm run dev
    networks:
      - app
    depends_on:
      - mysql
    ports:
      - '3456:3456'
    volumes:
      - .:/home/app
      - /home/app/node_modules

  mysql:
    image: mysql:5.6
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - '3306:3306'

networks:
  app:
